from rest_framework import serializers

class PredictSerializer(serializers.Serializer):
    tipe_agunan = serializers.CharField()
    kondisi_agunan = serializers.CharField()
    kemudahan_dijual_kembali = serializers.CharField()
    status_lunas_agunan = serializers.CharField()
    agunan_dibanyak_pinjaman = serializers.CharField()
    kesediaan_untuk_digadaikan = serializers.CharField()
    jenis_asset_bergerak_atau_tidak = serializers.CharField()
    riwayat_agunan_sebelumnya = serializers.CharField()
    status_kepemilikan_asset = serializers.CharField()
    asuransi_agunan = serializers.BooleanField()
    pekerjaan = serializers.CharField()
    tujuan_pinjaman = serializers.CharField()
    agunan = serializers.CharField()
    merk_aset = serializers.CharField()
    status_agunan_terburuk = serializers.FloatField()
    jumlah_agunan = serializers.FloatField()
    nilai_agunan = serializers.FloatField()
    tenor = serializers.FloatField()
    usia_agunan = serializers.FloatField()
    aset_maya = serializers.FloatField()
    kenaikan_nilai_property_agunan = serializers.FloatField()
    surat_berharga = serializers.FloatField()
